### ISSUE TITLE
Touch Controls - Dragging

### ISSUE THREAD

**Issue by jsf62592** [jsf62592/Blight-Crusaders#11]
In order to do an attack, players will have to drag from a player character to an enemy. Once this happens, both player character and enemy character should change colors for a short time (blue - pc, red - enemy). If the player character is selected, but it isn't dragged to an enemy character, nothing should happen

**Comment by jpmeenagh** [comment]
-reminder to self: this shouldn't work when enemy off cooldown (cooldown = 0)
