### ISSUE TITLE
Touch Controls - Gesture movement

### ISSUE THREAD

**Issue by jsf62592** [jsf62592/Blight-Crusaders#20]
After a player has decided to attack an enemy, implement a basic gesture recognition system. The system should be able to detect two unique gestures, such as a circle and a cross. Print out a message if the gesture is recognized.

**Comment by jpmeenagh** [comment]
I settled on the simplified system we discussed where it merely detects a movement up or down. More complex gestures could still be doable but would be janky significantly more coding and test time.
