### ISSUE TITLE
Interface Stuff

### ISSUE THREAD

**Issue by jsf62592** [jsf62592/Blight-Crusaders#30]
Move icons to bottom of the screen, add cooldown stuff, screen transitions

**Comment by jpmeenagh** [comment]
done:
https://github.com/jsf62592/Blight-Crusaders/commit/9a58bd341d5b49c4b857f9e8db562ac158d888f5
https://github.com/jsf62592/Blight-Crusaders/commit/87fb3459415154d9eb9494f37f577a6083dfeb6a
